#!/usr/bin/env bash

#Este script es util para crear muchos archivos o modificarlos

echo "Bien ejecutado"

arr=(14 2 12)

PROGRAMS=(loop_merge loop_merge-opt access_seq access_strided soa aos product product_block)


for((i==0;i<8;i++))
do
    echo ${PROGRAMS[i]}
    
done

echo "Done"
