#!/usr/bin/env bash

#Este script es util para crear muchos archivos o modificarlos

echo "Do you want to create new files? Y/n"
read answer
answer=${answer,,} #UPPER To lower

if [ "$answer" = "y" ]
then
  echo "Where?"
  read ubication
  cd "${ubication//\~/$HOME}"
  echo "How many?"
  read numberFiles
  echo "Name?"
  read name
  echo "Extension? (Don't forget the initial point)"
  read extension
  echo "Content?"
  read content

#Creation of files
  for ((i==1 ; i<=numberFiles; i++))
  do
    touch $name$i$extension
    echo "$content">$name$i$extension
  done
else
  echo "Modification of files:"
  echo "Where?"
  read ubication
  cd "${ubication//\~/$HOME}"
  echo "Extension? (Don't forget the initial point)"
  read extension
  echo "Word to change:"
  read Name1
  echo "New word: "
  read Name2

    find . -type f -name "*$extension" | xargs sed -i "s/$Name1/$Name2/g"

fi

echo "Done"
