#!/usr/bin/env bash

#Este script es util para crear el mismo archivo dentro de las carpetas
#que se encuentran en la direccion introducida

echo "Where?"
read ubication

cd "${ubication//\~/$HOME}"

echo "File name:"
read fName


#Creation of files
find . -type d -exec touch {}/$fName \;


echo "Done"
