#!/usr/bin/env bash

#Este script es util para crear la misma subcarpeta dentro de las carpetas
#que se encuentran en la direccion introducida

echo "Where?"
read ubication

cd "${ubication//\~/$HOME}"

echo "Folder name:"
read fName


#Creation of files
find . -mindepth 1 -maxdepth 1 -type d -exec mkdir {}/$fName \;


echo "Done"
