#!/usr/bin/env bash

#Script para crear carpetas para guardar resultados

NUM_EXAMPLES="6"  # Numero de ejemplos por heuristica
HEURISTICS=(0.01 0.25 0.5 0.75 0.9)  # Heuristicas utilizadas para las pruebas
TIME_THRESH="400"  # Tiempo maximo de espera para un test


# Pruebas de heuristica
for ((h=0; h < "${#HEURISTICS[*]}"; h++))
do
    echo ${HEURISTICS[*]}
    for ((i=10; i <= 70; i+=20))
    do
        echo "PRUEBA $i"
        mkdir $i-${HEURISTICS[h]}
    done
    echo "-------------------------------"
    echo ""

done
